db:
  image: postgres
  container_name: askci_postgres

uwsgi:
  restart: always
  container_name: askci_base
  build: ../
  volumes:
    - ../:/code
    - ../static:/var/www/static
    # uncomment for PAM auth
    #- /etc/passwd:/etc/passwd 
    #- /etc/shadow:/etc/shadow
  env_file:
    - ../.env
  links:
    - redis
    - db

nginx:
  restart: always
  container_name: askci_nginx
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ../docker/uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    - /etc/ssl/certs:/etc/ssl/certs:ro
    - /etc/ssl/private:/etc/ssl/private:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db

redis:
  restart: always
  image: redis:latest

scheduler:
  build: ../
  container_name: askci_scheduler
  command: python /code/manage.py rqscheduler
  volumes:
    - ../:/code
  env_file:
    - ../.env
  volumes_from:
    - uwsgi
  links:
    - redis
    - db

worker:
  build: ../
  container_name: askci_worker
  command: python /code/manage.py rqworker default
  env_file:
    - ../.env
  volumes:
    - ../:/code
  volumes_from:
    - uwsgi
  links:
    - redis
    - db
